# Generated by Django 4.1.3 on 2022-12-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tobacco_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['age', 'gender', 'tobacco_status'], name='example_quo_age_08504d_idx'),
        ),
    ]
