name: Terraform
on: [push]
env:
  PROJECT_ID: chmoder
  GAR_LOCATION: us-central1
  REPOSITORY: chmoder
  IMAGE: main
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .terraform
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.TERRAFORM_ADMIN_SA_KEY }}'
    - uses: hashicorp/setup-terraform@v2
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color -auto-approve
  build-and-push-django:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.TERRAFORM_ADMIN_SA_KEY }}'
        token_format: 'access_token'
    - uses: 'docker/login-action@v2'
      name: 'Docker login'
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Docker Build
      id: docker-build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          -f .docker/Dockerfile .
   
    - name: 'Docker push'
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
  deploy-django:
    needs: build-and-push-django
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.TERRAFORM_ADMIN_SA_KEY }}'
    - uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
        service: 'drf-example'
        flags: '--add-cloudsql-instances=chmoder:us-central1:drf-example-instance-1'
        env_vars: |
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_PORT=5432
          GS_BUCKET_NAME=${{ secrets.GS_BUCKET_NAME }}
          CLOUDRUN_SERVICE_URL=https://drf-example.chmoder.org
          DEBUG=True
  deploy-angular:
    needs: build-and-push-django
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.TERRAFORM_ADMIN_SA_KEY }}'

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install and npm run build
        run: |
          npm ci
          npm run build:ci

      - name: upload-files
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '/build/dist'
          destination: 'chmoder-drf-example/app'