name: Terraform
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .terraform
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.TERRAFORM_ADMIN_SA_KEY }}'
    - uses: hashicorp/setup-terraform@v2
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color -auto-approve
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.TERRAFORM_ADMIN_SA_KEY }}'

    - name: Docker Build
      id: docker-build
      run: docker build -f ./docker/Dockerfile .
   
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'